name: stapleui
description: "The User Interface for the Space Traders Automated PLanning Engine (STAPLE)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
  flutter: 3.24.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
  mockito: ^5.0.16

flutter:
  uses-material-design: true
