name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./stapleui

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.1.1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version #TODO: Remove this
      - run: flutter build windows
