name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.1.1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: stapleui/pubspec.yaml
      - name: Flutter Build Windows
        working-directory: ./stapleui
        run: flutter build windows
      - name: Upload UI Executable
        uses: actions/upload-artifact@v4
        with:
          name: StapleUI.exe
          path: ${{ github.workspace }}\stapleui\build\windows\x64\runner\Release\stapleui.exe
