name: Build Native Executable

on:
  # Trigger the workflow manually
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        graalvm-version: '22.3.0'
        java-version: '17'

    - name: Set up cache for Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Quarkus native executable
        run: ./buildExecutable.sh

    - name: Upload native executable
        uses: actions/upload-artifact@v2
        with:
          name: quarkus-app
          path: build/StapleApplication-runner